name: Trunk Check

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch: {}

jobs:
  trunk:
    name: Trunk Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v3
        with:
          path: local
          key: cpm-trunk-${{ runner.os }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Use local Perl packages
        run: |
          echo "$GITHUB_WORKSPACE/local/bin" | tee -a $GITHUB_PATH
          echo "PERL5LIB=$GITHUB_WORKSPACE/local/lib/perl5" | tee -a $GITHUB_ENV

      - name: Install cpm
        run: curl -sL https://git.io/cpm | perl - install --color --no-test --show-build-log-on-failure App::cpm

      - name: Install Module::Build
        run: cpm install --color --with-recommends --no-test --show-build-log-on-failure Module::Build

      - name: Generate meta data
        run: |
          perl Build.PL
          perl Build distmeta

      - name: Install required dependencies
        run: cpm install --color --with-recommends --no-test --show-build-log-on-failure .

      - name: Install linters
        run: cpm install --color --no-test --show-build-log-on-failure Perl::Critic Perl::Critic::Community Perl::Tidy

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: all
