name: Trunk Check

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch: {}

jobs:
  trunk:
    name: Trunk Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libperl-critic-perl perltidy

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: all
