name: Trunk Check

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch: {}

jobs:
  trunk:
    name: Trunk Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v3
        with:
          path: ~/.cpanm/sources
          key: cpanm-${{ runner.os }}-trunk
          restore-keys: |
            cpanm-${{ runner.os }}-

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install cpanmw
        run: curl -L cpanmin.us | perl - --sudo --notest --skip-satisfied App::cpanmw

      - name: Install linters
        run: cpanmw --sudo --notest --skip-satisfied Perl::Critic Perl::Critic::Community Perl::Tidy

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: all
